"""change request table for the natural-language editor

Revision ID: 16a6d6eba222
Revises: 96a22808bf40
Create Date: 2026-08-24 15:55:32.013359
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '16a6d6eba222'
down_revision: str | None = '96a22808bf40'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('planner_backend', sa.String(length=30), nullable=False),
    sa.Column('planner_model', sa.String(length=60), nullable=True),
    sa.Column('target_table', sa.String(length=64), nullable=False),
    sa.Column('statement_kind', sa.String(length=10), nullable=False),
    sa.Column('affected_count', sa.Integer(), nullable=False),
    sa.Column('before_rows', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_rows', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('diff', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('before_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PREVIEWED', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['app_user.id'], name=op.f('fk_change_request_requested_by_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_request'))
    )
    op.create_index(op.f('ix_change_request_requested_by_user_id'), 'change_request', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_change_request_status'), 'change_request', ['status'], unique=False)
    op.create_index('ix_change_request_status_created', 'change_request', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_change_request_status_created', table_name='change_request')
    op.drop_index(op.f('ix_change_request_status'), table_name='change_request')
    op.drop_index(op.f('ix_change_request_requested_by_user_id'), table_name='change_request')
    op.drop_table('change_request')
    # ### end Alembic commands ###
