"""simplified schema: companies, deals, thirteen tables

Revision ID: 577ee9e69ca9
Revises: 
Create Date: 2026-09-08 12:48:02.661688
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '577ee9e69ca9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=240), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=16), server_default='MEMBER', nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email', name='uq_app_user_email')
    )
    op.create_table('reference_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=24), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['reference_item.id'], name=op.f('fk_reference_item_parent_id_reference_item'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_item')),
    sa.UniqueConstraint('domain', 'code', name='uq_reference_item_domain_code')
    )
    op.create_index(op.f('ix_reference_item_domain'), 'reference_item', ['domain'], unique=False)
    op.create_index('ix_reference_item_domain_active', 'reference_item', ['domain', 'is_active'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('legal_name', sa.String(length=240), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=240), nullable=True),
    sa.Column('buys', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sells', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='LEAD', nullable=False),
    sa.Column('tax_id', sa.String(length=40), nullable=True),
    sa.Column('year_established', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.String(length=300), nullable=True),
    sa.Column('quality_requirements', sa.Text(), nullable=True),
    sa.Column('capacity_notes', sa.Text(), nullable=True),
    sa.Column('machinery_notes', sa.Text(), nullable=True),
    sa.Column('moq_notes', sa.String(length=300), nullable=True),
    sa.Column('lead_time_notes', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['reference_item.id'], name=op.f('fk_company_country_id_reference_item'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company')),
    sa.UniqueConstraint('name', 'city', name='uq_company_name_city')
    )
    op.create_index(op.f('ix_company_city'), 'company', ['city'], unique=False)
    op.create_index(op.f('ix_company_country_id'), 'company', ['country_id'], unique=False)
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_index('ix_company_role_status', 'company', ['sells', 'buys', 'status'], unique=False)
    op.create_index(op.f('ix_company_status'), 'company', ['status'], unique=False)
    op.create_table('deal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deal_no', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('currency_id', sa.Uuid(), nullable=True),
    sa.Column('incoterm_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='LEAD', nullable=False),
    sa.Column('lost_reason', sa.String(length=400), nullable=True),
    sa.Column('target_ship_date', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'LOST' OR lost_reason IS NOT NULL", name=op.f('ck_deal_deal_lost_needs_reason')),
    sa.ForeignKeyConstraint(['currency_id'], ['reference_item.id'], name=op.f('fk_deal_currency_id_reference_item'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incoterm_id'], ['reference_item.id'], name=op.f('fk_deal_incoterm_id_reference_item'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], name=op.f('fk_deal_owner_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['reference_item.id'], name=op.f('fk_deal_product_id_reference_item'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal')),
    sa.UniqueConstraint('deal_no', name='uq_deal_no')
    )
    op.create_index(op.f('ix_deal_last_activity_at'), 'deal', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_deal_owner_user_id'), 'deal', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_deal_product_id'), 'deal', ['product_id'], unique=False)
    op.create_index(op.f('ix_deal_status'), 'deal', ['status'], unique=False)
    op.create_index('ix_deal_status_ship', 'deal', ['status', 'target_ship_date'], unique=False)
    op.create_index(op.f('ix_deal_target_ship_date'), 'deal', ['target_ship_date'], unique=False)
    op.create_table('activity_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], name=op.f('fk_activity_log_actor_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_activity_log_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], name=op.f('fk_activity_log_deal_id_deal'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log'))
    )
    op.create_index('ix_activity_deal_created', 'activity_log', ['deal_id', 'created_at'], unique=False)
    op.create_index('ix_activity_entity', 'activity_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_activity_log_action'), 'activity_log', ['action'], unique=False)
    op.create_index(op.f('ix_activity_log_company_id'), 'activity_log', ['company_id'], unique=False)
    op.create_index(op.f('ix_activity_log_deal_id'), 'activity_log', ['deal_id'], unique=False)
    op.create_table('company_certification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('certification_id', sa.Uuid(), nullable=False),
    sa.Column('reference_no', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['certification_id'], ['reference_item.id'], name=op.f('fk_company_certification_certification_id_reference_item'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_certification_company_id_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_certification')),
    sa.UniqueConstraint('company_id', 'certification_id', name='uq_company_certification')
    )
    op.create_index(op.f('ix_company_certification_certification_id'), 'company_certification', ['certification_id'], unique=False)
    op.create_index(op.f('ix_company_certification_company_id'), 'company_certification', ['company_id'], unique=False)
    op.create_table('company_client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_client_company_id_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_client')),
    sa.UniqueConstraint('company_id', 'client_name', name='uq_company_client')
    )
    op.create_index(op.f('ix_company_client_company_id'), 'company_client', ['company_id'], unique=False)
    op.create_table('company_process',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=False),
    sa.Column('monthly_capacity', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_order_qty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_process_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['reference_item.id'], name=op.f('fk_company_process_process_id_reference_item'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_process')),
    sa.UniqueConstraint('company_id', 'process_id', name='uq_company_process')
    )
    op.create_index(op.f('ix_company_process_company_id'), 'company_process', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_process_process_id'), 'company_process', ['process_id'], unique=False)
    op.create_table('company_product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_company_product_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['reference_item.id'], name=op.f('fk_company_product_product_id_reference_item'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_product')),
    sa.UniqueConstraint('company_id', 'product_id', name='uq_company_product')
    )
    op.create_index(op.f('ix_company_product_company_id'), 'company_product', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_product_product_id'), 'company_product', ['product_id'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=240), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_contact_company_id_company'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact'))
    )
    op.create_index(op.f('ix_contact_company_id'), 'contact', ['company_id'], unique=False)
    op.create_table('deal_party',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('process_id', sa.Uuid(), nullable=True),
    sa.Column('sequence', sa.Integer(), server_default='1', nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('resale_unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('commission_basis', sa.String(length=16), server_default='NONE', nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('commission_status', sa.String(length=16), server_default='NOT_DUE', nullable=False),
    sa.Column('invoiced_on', sa.Date(), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=True),
    sa.Column('ship_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("commission_basis <> 'MARGIN' OR (unit_price IS NOT NULL AND resale_unit_price IS NOT NULL)", name=op.f('ck_deal_party_deal_party_margin_needs_both_prices')),
    sa.CheckConstraint("commission_basis <> 'PERCENTAGE' OR commission_pct IS NOT NULL", name=op.f('ck_deal_party_deal_party_percentage_needs_pct')),
    sa.CheckConstraint("commission_status NOT IN ('INVOICED','RECEIVED') OR commission_amount IS NOT NULL", name=op.f('ck_deal_party_deal_party_billed_needs_amount')),
    sa.CheckConstraint('received_on IS NULL OR invoiced_on IS NULL OR received_on >= invoiced_on', name=op.f('ck_deal_party_deal_party_received_after_invoiced')),
    sa.CheckConstraint('resale_unit_price IS NULL OR unit_price IS NULL OR resale_unit_price >= unit_price', name=op.f('ck_deal_party_deal_party_margin_not_negative')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_deal_party_company_id_company'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], name=op.f('fk_deal_party_deal_id_deal'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_id'], ['reference_item.id'], name=op.f('fk_deal_party_process_id_reference_item'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_party')),
    sa.UniqueConstraint('deal_id', 'company_id', 'role', name='uq_deal_party')
    )
    op.create_index(op.f('ix_deal_party_commission_status'), 'deal_party', ['commission_status'], unique=False)
    op.create_index(op.f('ix_deal_party_company_id'), 'deal_party', ['company_id'], unique=False)
    op.create_index(op.f('ix_deal_party_deal_id'), 'deal_party', ['deal_id'], unique=False)
    op.create_index('ix_deal_party_ledger', 'deal_party', ['commission_status', 'received_on'], unique=False)
    op.create_index(op.f('ix_deal_party_received_on'), 'deal_party', ['received_on'], unique=False)
    op.create_index(op.f('ix_deal_party_role'), 'deal_party', ['role'], unique=False)
    op.create_index(op.f('ix_deal_party_ship_date'), 'deal_party', ['ship_date'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=24), server_default='OTHER', nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('deal_id IS NOT NULL OR company_id IS NOT NULL', name=op.f('ck_document_document_needs_an_owner')),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_document_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], name=op.f('fk_document_deal_id_deal'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['app_user.id'], name=op.f('fk_document_uploaded_by_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_company_id'), 'document', ['company_id'], unique=False)
    op.create_index(op.f('ix_document_deal_id'), 'document', ['deal_id'], unique=False)
    op.create_index('ix_document_deal_kind', 'document', ['deal_id', 'kind'], unique=False)
    op.create_index(op.f('ix_document_kind'), 'document', ['kind'], unique=False)
    op.create_table('deal_milestone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('deal_party_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sequence', sa.Integer(), server_default='1', nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'DONE' OR actual_date IS NOT NULL", name=op.f('ck_deal_milestone_milestone_done_needs_date')),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], name=op.f('fk_deal_milestone_deal_id_deal'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_party_id'], ['deal_party.id'], name=op.f('fk_deal_milestone_deal_party_id_deal_party'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], name=op.f('fk_deal_milestone_owner_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_milestone'))
    )
    op.create_index(op.f('ix_deal_milestone_deal_id'), 'deal_milestone', ['deal_id'], unique=False)
    op.create_index(op.f('ix_deal_milestone_planned_date'), 'deal_milestone', ['planned_date'], unique=False)
    op.create_index(op.f('ix_deal_milestone_status'), 'deal_milestone', ['status'], unique=False)
    op.create_index('ix_milestone_due', 'deal_milestone', ['status', 'planned_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_milestone_due', table_name='deal_milestone')
    op.drop_index(op.f('ix_deal_milestone_status'), table_name='deal_milestone')
    op.drop_index(op.f('ix_deal_milestone_planned_date'), table_name='deal_milestone')
    op.drop_index(op.f('ix_deal_milestone_deal_id'), table_name='deal_milestone')
    op.drop_table('deal_milestone')
    op.drop_index(op.f('ix_document_kind'), table_name='document')
    op.drop_index('ix_document_deal_kind', table_name='document')
    op.drop_index(op.f('ix_document_deal_id'), table_name='document')
    op.drop_index(op.f('ix_document_company_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_deal_party_ship_date'), table_name='deal_party')
    op.drop_index(op.f('ix_deal_party_role'), table_name='deal_party')
    op.drop_index(op.f('ix_deal_party_received_on'), table_name='deal_party')
    op.drop_index('ix_deal_party_ledger', table_name='deal_party')
    op.drop_index(op.f('ix_deal_party_deal_id'), table_name='deal_party')
    op.drop_index(op.f('ix_deal_party_company_id'), table_name='deal_party')
    op.drop_index(op.f('ix_deal_party_commission_status'), table_name='deal_party')
    op.drop_table('deal_party')
    op.drop_index(op.f('ix_contact_company_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_company_product_product_id'), table_name='company_product')
    op.drop_index(op.f('ix_company_product_company_id'), table_name='company_product')
    op.drop_table('company_product')
    op.drop_index(op.f('ix_company_process_process_id'), table_name='company_process')
    op.drop_index(op.f('ix_company_process_company_id'), table_name='company_process')
    op.drop_table('company_process')
    op.drop_index(op.f('ix_company_client_company_id'), table_name='company_client')
    op.drop_table('company_client')
    op.drop_index(op.f('ix_company_certification_company_id'), table_name='company_certification')
    op.drop_index(op.f('ix_company_certification_certification_id'), table_name='company_certification')
    op.drop_table('company_certification')
    op.drop_index(op.f('ix_activity_log_deal_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_company_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_action'), table_name='activity_log')
    op.drop_index('ix_activity_entity', table_name='activity_log')
    op.drop_index('ix_activity_deal_created', table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_deal_target_ship_date'), table_name='deal')
    op.drop_index('ix_deal_status_ship', table_name='deal')
    op.drop_index(op.f('ix_deal_status'), table_name='deal')
    op.drop_index(op.f('ix_deal_product_id'), table_name='deal')
    op.drop_index(op.f('ix_deal_owner_user_id'), table_name='deal')
    op.drop_index(op.f('ix_deal_last_activity_at'), table_name='deal')
    op.drop_table('deal')
    op.drop_index(op.f('ix_company_status'), table_name='company')
    op.drop_index('ix_company_role_status', table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_index(op.f('ix_company_country_id'), table_name='company')
    op.drop_index(op.f('ix_company_city'), table_name='company')
    op.drop_table('company')
    op.drop_index('ix_reference_item_domain_active', table_name='reference_item')
    op.drop_index(op.f('ix_reference_item_domain'), table_name='reference_item')
    op.drop_table('reference_item')
    op.drop_table('app_user')
    # ### end Alembic commands ###
