"""document_chunk and extraction status: the retrieval layer

Revision ID: 6e92e5e88919
Revises: 577ee9e69ca9
Create Date: 2026-09-09 12:45:32.887226
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
# Autogenerate emits pgvector.sqlalchemy.Vector but does not import it.
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '6e92e5e88919'
down_revision: str | None = '577ee9e69ca9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The column type below does not exist until this runs. Requires a superuser the first
    # time; on a managed Postgres it is usually pre-installed.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True),
    sa.Column('embedding_model', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_document_chunk_company_id_company'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], name=op.f('fk_document_chunk_deal_id_deal'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_chunk_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunk')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunk_index')
    )
    op.create_index(op.f('ix_document_chunk_company_id'), 'document_chunk', ['company_id'], unique=False)
    op.create_index(op.f('ix_document_chunk_deal_id'), 'document_chunk', ['deal_id'], unique=False)
    op.create_index(op.f('ix_document_chunk_document_id'), 'document_chunk', ['document_id'], unique=False)
    op.create_index('ix_document_chunk_tsv', 'document_chunk', ['content_tsv'], unique=False, postgresql_using='gin')
    op.add_column('document', sa.Column('extraction_status', sa.String(length=16), server_default='PENDING', nullable=False))
    op.add_column('document', sa.Column('extraction_error', sa.Text(), nullable=True))
    op.create_index(op.f('ix_document_extraction_status'), 'document', ['extraction_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # The extension is deliberately left in place — dropping it would break any other
    # database object depending on it.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_extraction_status'), table_name='document')
    op.drop_column('document', 'extraction_error')
    op.drop_column('document', 'extraction_status')
    op.drop_index('ix_document_chunk_tsv', table_name='document_chunk', postgresql_using='gin')
    op.drop_index(op.f('ix_document_chunk_document_id'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_deal_id'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_company_id'), table_name='document_chunk')
    op.drop_table('document_chunk')
    # ### end Alembic commands ###
