"""initial schema

Revision ID: 96a22808bf40
Revises: 
Create Date: 2026-08-24 15:05:56.812180
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '96a22808bf40'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Organization <-> app_user is a genuine reference cycle, so those three FKs are marked
# use_alter on the model. Alembic's autogenerate silently omits use_alter foreign keys — it
# neither inlines them in create_table nor emits them afterwards — so without these explicit
# calls the columns would carry no referential integrity at all in Postgres.
_CYCLIC_FKS = [
    ("fk_organization_owner_user_id_app_user", "owner_user_id"),
    ("fk_organization_created_by_user_id_app_user", "created_by_user_id"),
    ("fk_organization_verified_by_user_id_app_user", "verified_by_user_id"),
]


def _enable_pgvector() -> None:
    """Enable pgvector now so Phase 6 only has to add columns, not an extension.

    §8 says to enable it up front. Nothing depends on it yet, so a Postgres build without the
    extension available (a plain local install, as opposed to the pgvector image in
    docker-compose) is not a reason to fail the whole migration — it is a reason to say so.
    """
    bind = op.get_bind()
    available = bind.exec_driver_sql(
        "SELECT 1 FROM pg_available_extensions WHERE name = 'vector'"
    ).first()
    if available:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    else:
        print(
            "  note: pgvector is not available on this server; skipping CREATE EXTENSION. "
            "Install it before Phase 6 (the docker-compose db image already has it)."
        )


def upgrade() -> None:
    _enable_pgvector()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_key', sa.String(length=80), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=8), server_default='en', nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provider_template_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_template')),
    sa.UniqueConstraint('event_key', 'channel', 'language', name='uq_notification_template_event_channel_lang')
    )
    op.create_index(op.f('ix_notification_template_event_key'), 'notification_template', ['event_key'], unique=False)
    op.create_table('reference_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('path', sa.String(length=500), server_default='', nullable=False),
    sa.Column('depth', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['reference_item.id'], name=op.f('fk_reference_item_parent_id_reference_item'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_item')),
    sa.UniqueConstraint('domain', 'code', name='uq_reference_item_domain_code'),
    sa.UniqueConstraint('id', 'domain', name='uq_reference_item_id_domain')
    )
    op.create_index(op.f('ix_reference_item_domain'), 'reference_item', ['domain'], unique=False)
    op.create_index('ix_reference_item_domain_path', 'reference_item', ['domain', 'path'], unique=False)
    op.create_index(op.f('ix_reference_item_parent_id'), 'reference_item', ['parent_id'], unique=False)
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('legal_name', sa.String(length=240), nullable=False),
    sa.Column('trade_name', sa.String(length=240), nullable=True),
    sa.Column('country_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('gst_no', sa.String(length=30), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('iec_code', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=240), nullable=True),
    sa.Column('year_established', sa.Integer(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_internal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('import_batch_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['reference_item.id'], name=op.f('fk_organization_country_id_reference_item'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name='fk_organization_created_by_user_id_app_user', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], name='fk_organization_owner_user_id_app_user', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['app_user.id'], name='fk_organization_verified_by_user_id_app_user', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization')),
    sa.UniqueConstraint('gst_no', name='uq_organization_gst_no')
    )
    op.create_index(op.f('ix_organization_city'), 'organization', ['city'], unique=False)
    op.create_index(op.f('ix_organization_country_id'), 'organization', ['country_id'], unique=False)
    op.create_index(op.f('ix_organization_import_batch_id'), 'organization', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_organization_status'), 'organization', ['status'], unique=False)
    op.create_index(op.f('ix_organization_trade_name'), 'organization', ['trade_name'], unique=False)
    op.create_index(op.f('ix_organization_type'), 'organization', ['type'], unique=False)
    op.create_index('ix_organization_type_status', 'organization', ['type', 'status'], unique=False)
    op.create_table('reference_alias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=160), nullable=False),
    sa.Column('normalised', sa.String(length=160), nullable=False),
    sa.Column('language', sa.String(length=8), server_default='en', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['reference_item.id'], name=op.f('fk_reference_alias_item_id_reference_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_alias')),
    sa.UniqueConstraint('item_id', 'normalised', name='uq_reference_alias_item_normalised')
    )
    op.create_index(op.f('ix_reference_alias_normalised'), 'reference_alias', ['normalised'], unique=False)
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=240), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('language_pref', sa.String(length=8), server_default='en', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='INVITED', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role LIKE 'INTERNAL_%%' AND org_id IS NULL) OR (role NOT LIKE 'INTERNAL_%%' AND org_id IS NOT NULL)", name=op.f('ck_app_user_app_user_org_matches_role')),
    sa.CheckConstraint('email IS NOT NULL OR phone IS NOT NULL', name=op.f('ck_app_user_app_user_email_or_phone')),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_app_user_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email', name='uq_app_user_email'),
    sa.UniqueConstraint('phone', name='uq_app_user_phone')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=False)
    op.create_index(op.f('ix_app_user_org_id'), 'app_user', ['org_id'], unique=False)
    op.create_index('ix_app_user_org_role', 'app_user', ['org_id', 'role'], unique=False)
    op.create_index(op.f('ix_app_user_phone'), 'app_user', ['phone'], unique=False)
    op.create_index(op.f('ix_app_user_role'), 'app_user', ['role'], unique=False)
    op.create_index(op.f('ix_app_user_status'), 'app_user', ['status'], unique=False)
    op.create_table('brand_category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('product_category_id', sa.Uuid(), nullable=False),
    sa.Column('product_category_domain', sa.String(length=40), server_default='PRODUCT_CATEGORY', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("product_category_domain = 'PRODUCT_CATEGORY'", name=op.f('ck_brand_category_product_category_domain')),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_brand_category_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id', 'product_category_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_brand_category_product_category_reference_item', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_category')),
    sa.UniqueConstraint('org_id', 'product_category_id', name='uq_brand_category_org_cat')
    )
    op.create_index(op.f('ix_brand_category_org_id'), 'brand_category', ['org_id'], unique=False)
    op.create_index(op.f('ix_brand_category_product_category_id'), 'brand_category', ['product_category_id'], unique=False)
    op.create_table('brand_excluded_country',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('country_domain', sa.String(length=40), server_default='COUNTRY', nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("country_domain = 'COUNTRY'", name=op.f('ck_brand_excluded_country_country_domain')),
    sa.ForeignKeyConstraint(['country_id', 'country_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_brand_excluded_country_country_reference_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_brand_excluded_country_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_excluded_country')),
    sa.UniqueConstraint('org_id', 'country_id', name='uq_brand_excluded_country_org_country')
    )
    op.create_index(op.f('ix_brand_excluded_country_country_id'), 'brand_excluded_country', ['country_id'], unique=False)
    op.create_index(op.f('ix_brand_excluded_country_org_id'), 'brand_excluded_country', ['org_id'], unique=False)
    op.create_table('brand_required_certification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('certification_id', sa.Uuid(), nullable=False),
    sa.Column('certification_domain', sa.String(length=40), server_default='CERTIFICATION', nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("certification_domain = 'CERTIFICATION'", name=op.f('ck_brand_required_certification_certification_domain')),
    sa.ForeignKeyConstraint(['certification_id', 'certification_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_brand_required_certification_certification_reference_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_brand_required_certification_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_required_certification')),
    sa.UniqueConstraint('org_id', 'certification_id', name='uq_brand_req_cert_org_cert')
    )
    op.create_index(op.f('ix_brand_required_certification_certification_id'), 'brand_required_certification', ['certification_id'], unique=False)
    op.create_index(op.f('ix_brand_required_certification_org_id'), 'brand_required_certification', ['org_id'], unique=False)
    op.create_table('brand_target_market',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('country_domain', sa.String(length=40), server_default='COUNTRY', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("country_domain = 'COUNTRY'", name=op.f('ck_brand_target_market_country_domain')),
    sa.ForeignKeyConstraint(['country_id', 'country_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_brand_target_market_country_reference_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_brand_target_market_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_target_market')),
    sa.UniqueConstraint('org_id', 'country_id', name='uq_brand_target_market_org_country')
    )
    op.create_index(op.f('ix_brand_target_market_country_id'), 'brand_target_market', ['country_id'], unique=False)
    op.create_index(op.f('ix_brand_target_market_org_id'), 'brand_target_market', ['org_id'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=240), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('language_pref', sa.String(length=8), server_default='en', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_contact_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact'))
    )
    op.create_index(op.f('ix_contact_org_id'), 'contact', ['org_id'], unique=False)
    op.create_table('supplier_capability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('product_category_id', sa.Uuid(), nullable=False),
    sa.Column('product_category_domain', sa.String(length=40), server_default='PRODUCT_CATEGORY', nullable=False),
    sa.Column('gsm_min', sa.Integer(), nullable=True),
    sa.Column('gsm_max', sa.Integer(), nullable=True),
    sa.Column('size_range', sa.String(length=160), nullable=True),
    sa.Column('price_band_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_band_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency_id', sa.Uuid(), nullable=True),
    sa.Column('currency_domain', sa.String(length=40), server_default='CURRENCY', nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='SELF_REPORTED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency_domain = 'CURRENCY'", name=op.f('ck_supplier_capability_currency_domain')),
    sa.CheckConstraint("product_category_domain = 'PRODUCT_CATEGORY'", name=op.f('ck_supplier_capability_product_category_domain')),
    sa.CheckConstraint('(price_band_min IS NULL AND price_band_max IS NULL) OR currency_id IS NOT NULL', name=op.f('ck_supplier_capability_supplier_capability_price_needs_currency')),
    sa.CheckConstraint('gsm_min IS NULL OR gsm_max IS NULL OR gsm_min <= gsm_max', name=op.f('ck_supplier_capability_supplier_capability_gsm_order')),
    sa.CheckConstraint('price_band_min IS NULL OR price_band_max IS NULL OR price_band_min <= price_band_max', name=op.f('ck_supplier_capability_supplier_capability_price_order')),
    sa.ForeignKeyConstraint(['currency_id', 'currency_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_supplier_capability_currency_reference_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_supplier_capability_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id', 'product_category_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_supplier_capability_product_category_reference_item', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_capability')),
    sa.UniqueConstraint('org_id', 'product_category_id', name='uq_supplier_capability_org_cat')
    )
    op.create_index(op.f('ix_supplier_capability_currency_id'), 'supplier_capability', ['currency_id'], unique=False)
    op.create_index(op.f('ix_supplier_capability_org_id'), 'supplier_capability', ['org_id'], unique=False)
    op.create_index(op.f('ix_supplier_capability_product_category_id'), 'supplier_capability', ['product_category_id'], unique=False)
    op.create_table('supplier_capacity_calendar',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('process_type_id', sa.Uuid(), nullable=False),
    sa.Column('process_type_domain', sa.String(length=40), server_default='PROCESS_TYPE', nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('total_qty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('committed_qty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('available_qty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('uom', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='SELF_REPORTED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("process_type_domain = 'PROCESS_TYPE'", name=op.f('ck_supplier_capacity_calendar_process_type_domain')),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_supplier_capacity_calendar_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_type_id', 'process_type_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_supplier_capacity_calendar_process_type_reference_item', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_capacity_calendar')),
    sa.UniqueConstraint('org_id', 'process_type_id', 'month', name='uq_supplier_capacity_org_process_month')
    )
    op.create_index(op.f('ix_supplier_capacity_calendar_month'), 'supplier_capacity_calendar', ['month'], unique=False)
    op.create_index(op.f('ix_supplier_capacity_calendar_org_id'), 'supplier_capacity_calendar', ['org_id'], unique=False)
    op.create_index(op.f('ix_supplier_capacity_calendar_process_type_id'), 'supplier_capacity_calendar', ['process_type_id'], unique=False)
    op.create_table('supplier_export_market',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('country_domain', sa.String(length=40), server_default='COUNTRY', nullable=False),
    sa.Column('years_shipping', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("country_domain = 'COUNTRY'", name=op.f('ck_supplier_export_market_country_domain')),
    sa.ForeignKeyConstraint(['country_id', 'country_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_supplier_export_market_country_reference_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_supplier_export_market_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_export_market')),
    sa.UniqueConstraint('org_id', 'country_id', name='uq_supplier_export_market_org_country')
    )
    op.create_index(op.f('ix_supplier_export_market_country_id'), 'supplier_export_market', ['country_id'], unique=False)
    op.create_index(op.f('ix_supplier_export_market_org_id'), 'supplier_export_market', ['org_id'], unique=False)
    op.create_table('supplier_machine',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('machine_type_id', sa.Uuid(), nullable=False),
    sa.Column('machine_type_domain', sa.String(length=40), server_default='MACHINERY_TYPE', nullable=False),
    sa.Column('make', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('gauge', sa.String(length=40), nullable=True),
    sa.Column('diameter', sa.String(length=40), nullable=True),
    sa.Column('year_of_make', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='SELF_REPORTED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("machine_type_domain = 'MACHINERY_TYPE'", name=op.f('ck_supplier_machine_machine_type_domain')),
    sa.CheckConstraint('count > 0', name=op.f('ck_supplier_machine_supplier_machine_count_positive')),
    sa.ForeignKeyConstraint(['machine_type_id', 'machine_type_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_supplier_machine_machine_type_reference_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_supplier_machine_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_machine'))
    )
    op.create_index(op.f('ix_supplier_machine_machine_type_id'), 'supplier_machine', ['machine_type_id'], unique=False)
    op.create_index(op.f('ix_supplier_machine_org_id'), 'supplier_machine', ['org_id'], unique=False)
    op.create_table('supplier_performance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_months', sa.Integer(), server_default='1', nullable=False),
    sa.Column('orders_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('on_time_delivery_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_delay_days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('final_inspection_pass_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('defect_rate_ppm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sample_approval_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_sample_turnaround_days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('quote_response_time_hrs', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('quote_win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price_competitiveness_index', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('claims_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('composite_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_supplier_performance_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_performance')),
    sa.UniqueConstraint('org_id', 'period_start', 'period_months', name='uq_supplier_performance_org_period')
    )
    op.create_index(op.f('ix_supplier_performance_org_id'), 'supplier_performance', ['org_id'], unique=False)
    op.create_table('supplier_process',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('process_type_id', sa.Uuid(), nullable=False),
    sa.Column('process_type_domain', sa.String(length=40), server_default='PROCESS_TYPE', nullable=False),
    sa.Column('is_inhouse', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_subcontracted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('subcontractor_notes', sa.Text(), nullable=True),
    sa.Column('monthly_capacity_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('capacity_uom', sa.String(length=20), nullable=True),
    sa.Column('min_order_qty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('moq_uom', sa.String(length=20), nullable=True),
    sa.Column('standard_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('sample_lead_time_days', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), server_default='SELF_REPORTED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("process_type_domain = 'PROCESS_TYPE'", name=op.f('ck_supplier_process_process_type_domain')),
    sa.CheckConstraint('is_inhouse OR is_subcontracted', name=op.f('ck_supplier_process_supplier_process_inhouse_or_subcontracted')),
    sa.CheckConstraint('min_order_qty IS NULL OR moq_uom IS NOT NULL', name=op.f('ck_supplier_process_supplier_process_moq_needs_uom')),
    sa.CheckConstraint('monthly_capacity_value IS NULL OR capacity_uom IS NOT NULL', name=op.f('ck_supplier_process_supplier_process_capacity_needs_uom')),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_supplier_process_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_type_id', 'process_type_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_supplier_process_process_type_reference_item', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_process')),
    sa.UniqueConstraint('org_id', 'process_type_id', name='uq_supplier_process_org_process')
    )
    op.create_index('ix_supplier_process_filter', 'supplier_process', ['process_type_id', 'org_id'], unique=False)
    op.create_index(op.f('ix_supplier_process_org_id'), 'supplier_process', ['org_id'], unique=False)
    op.create_index(op.f('ix_supplier_process_process_type_id'), 'supplier_process', ['process_type_id'], unique=False)
    op.create_table('supplier_profile',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_tier_grade', sa.String(length=2), nullable=True),
    sa.Column('completeness_tier', sa.String(length=30), server_default='TIER_1_REGISTERED', nullable=False),
    sa.Column('completeness_pct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('export_experience_years', sa.Integer(), nullable=True),
    sa.Column('annual_turnover_band', sa.String(length=40), nullable=True),
    sa.Column('is_vertically_integrated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('subcontracting_policy', sa.String(length=30), nullable=True),
    sa.Column('capability_narrative', sa.Text(), nullable=True),
    sa.Column('narrative_language', sa.String(length=8), server_default='en', nullable=False),
    sa.Column('source', sa.String(length=20), server_default='SELF_REPORTED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completeness_pct >= 0 AND completeness_pct <= 100', name=op.f('ck_supplier_profile_supplier_profile_completeness_range')),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_supplier_profile_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('org_id', name=op.f('pk_supplier_profile'))
    )
    op.create_index(op.f('ix_supplier_profile_completeness_tier'), 'supplier_profile', ['completeness_tier'], unique=False)
    op.create_table('supplier_reference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=True),
    sa.Column('buyer_country_id', sa.Uuid(), nullable=True),
    sa.Column('buyer_country_domain', sa.String(length=40), server_default='COUNTRY', nullable=True),
    sa.Column('product_category_id', sa.Uuid(), nullable=True),
    sa.Column('product_category_domain', sa.String(length=40), server_default='PRODUCT_CATEGORY', nullable=True),
    sa.Column('annual_qty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('qty_uom', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_contactable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verification_status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("buyer_country_domain = 'COUNTRY'", name=op.f('ck_supplier_reference_buyer_country_domain')),
    sa.CheckConstraint("product_category_domain = 'PRODUCT_CATEGORY'", name=op.f('ck_supplier_reference_product_category_domain')),
    sa.ForeignKeyConstraint(['buyer_country_id', 'buyer_country_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_supplier_reference_buyer_country_reference_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_supplier_reference_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_category_id', 'product_category_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_supplier_reference_product_category_reference_item', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_reference'))
    )
    op.create_index(op.f('ix_supplier_reference_buyer_country_id'), 'supplier_reference', ['buyer_country_id'], unique=False)
    op.create_index(op.f('ix_supplier_reference_org_id'), 'supplier_reference', ['org_id'], unique=False)
    op.create_index(op.f('ix_supplier_reference_product_category_id'), 'supplier_reference', ['product_category_id'], unique=False)
    op.create_table('activity_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], name=op.f('fk_activity_log_actor_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_activity_log_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log'))
    )
    op.create_index(op.f('ix_activity_log_action'), 'activity_log', ['action'], unique=False)
    op.create_index(op.f('ix_activity_log_actor_user_id'), 'activity_log', ['actor_user_id'], unique=False)
    op.create_index('ix_activity_log_entity', 'activity_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_activity_log_org_created', 'activity_log', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_log_org_id'), 'activity_log', ['org_id'], unique=False)
    op.create_table('brand_supplier_reveal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand_org_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_org_id', sa.Uuid(), nullable=False),
    sa.Column('brand_sees_supplier', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('supplier_sees_brand', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('revealed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_org_id'], ['organization.id'], name=op.f('fk_brand_supplier_reveal_brand_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revealed_by_user_id'], ['app_user.id'], name=op.f('fk_brand_supplier_reveal_revealed_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_org_id'], ['organization.id'], name=op.f('fk_brand_supplier_reveal_supplier_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_supplier_reveal')),
    sa.UniqueConstraint('brand_org_id', 'supplier_org_id', name='uq_reveal_brand_supplier')
    )
    op.create_index(op.f('ix_brand_supplier_reveal_brand_org_id'), 'brand_supplier_reveal', ['brand_org_id'], unique=False)
    op.create_index(op.f('ix_brand_supplier_reveal_supplier_org_id'), 'brand_supplier_reveal', ['supplier_org_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('owner_type', sa.String(length=60), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_till', sa.Date(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_internal_only', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_document_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['app_user.id'], name=op.f('fk_document_uploaded_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['app_user.id'], name=op.f('fk_document_verified_by_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_checksum_sha256'), 'document', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_document_doc_type'), 'document', ['doc_type'], unique=False)
    op.create_index('ix_document_expiry_sweep', 'document', ['valid_till', 'verification_status'], unique=False)
    op.create_index(op.f('ix_document_org_id'), 'document', ['org_id'], unique=False)
    op.create_index('ix_document_owner', 'document', ['owner_type', 'owner_id'], unique=False)
    op.create_index(op.f('ix_document_valid_till'), 'document', ['valid_till'], unique=False)
    op.create_index(op.f('ix_document_verification_status'), 'document', ['verification_status'], unique=False)
    op.create_table('import_batch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('imported_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('total_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('row_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_by_user_id'], ['app_user.id'], name=op.f('fk_import_batch_imported_by_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batch'))
    )
    op.create_table('note',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal_only', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('mentions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['app_user.id'], name=op.f('fk_note_author_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_note_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note'))
    )
    op.create_index('ix_note_entity', 'note', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_note_org_id'), 'note', ['org_id'], unique=False)
    op.create_table('notification_outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_key', sa.String(length=80), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_address', sa.String(length=300), nullable=True),
    sa.Column('language', sa.String(length=8), server_default='en', nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('dedupe_key', sa.String(length=300), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['app_user.id'], name=op.f('fk_notification_outbox_recipient_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_outbox')),
    sa.UniqueConstraint('dedupe_key', name='uq_notification_outbox_dedupe_key')
    )
    op.create_index(op.f('ix_notification_outbox_channel'), 'notification_outbox', ['channel'], unique=False)
    op.create_index('ix_notification_outbox_dispatch', 'notification_outbox', ['status', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_notification_outbox_event_key'), 'notification_outbox', ['event_key'], unique=False)
    op.create_index('ix_notification_outbox_inbox', 'notification_outbox', ['recipient_user_id', 'channel', 'read_at'], unique=False)
    op.create_index(op.f('ix_notification_outbox_recipient_user_id'), 'notification_outbox', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_notification_outbox_scheduled_for'), 'notification_outbox', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_notification_outbox_status'), 'notification_outbox', ['status'], unique=False)
    op.create_table('notification_preference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_key', sa.String(length=80), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_notification_preference_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preference')),
    sa.UniqueConstraint('user_id', 'event_key', 'channel', name='uq_notif_pref_user_event_channel')
    )
    op.create_index(op.f('ix_notification_preference_user_id'), 'notification_preference', ['user_id'], unique=False)
    op.create_table('org_invite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=240), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('sent_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('send_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['app_user.id'], name=op.f('fk_org_invite_accepted_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_org_invite_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['app_user.id'], name=op.f('fk_org_invite_sent_by_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_invite'))
    )
    op.create_index(op.f('ix_org_invite_org_id'), 'org_invite', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_invite_token_hash'), 'org_invite', ['token_hash'], unique=False)
    op.create_table('otp_challenge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('destination', sa.String(length=240), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_otp_challenge_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_challenge'))
    )
    op.create_index(op.f('ix_otp_challenge_destination'), 'otp_challenge', ['destination'], unique=False)
    op.create_index(op.f('ix_otp_challenge_user_id'), 'otp_challenge', ['user_id'], unique=False)
    op.create_table('supplier_capability_construction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('construction_id', sa.Uuid(), nullable=False),
    sa.Column('construction_domain', sa.String(length=40), server_default='FABRIC_CONSTRUCTION', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("construction_domain = 'FABRIC_CONSTRUCTION'", name=op.f('ck_supplier_capability_construction_construction_domain')),
    sa.ForeignKeyConstraint(['capability_id'], ['supplier_capability.id'], name=op.f('fk_supplier_capability_construction_capability_id_supplier_capability'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['construction_id', 'construction_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_supplier_capability_construction_construction_reference_item', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_capability_construction')),
    sa.UniqueConstraint('capability_id', 'construction_id', name='uq_supplier_cap_construction')
    )
    op.create_index(op.f('ix_supplier_capability_construction_capability_id'), 'supplier_capability_construction', ['capability_id'], unique=False)
    op.create_index(op.f('ix_supplier_capability_construction_construction_id'), 'supplier_capability_construction', ['construction_id'], unique=False)
    op.create_table('supplier_capability_fibre',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('fibre_id', sa.Uuid(), nullable=False),
    sa.Column('fibre_domain', sa.String(length=40), server_default='FIBRE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fibre_domain = 'FIBRE'", name=op.f('ck_supplier_capability_fibre_fibre_domain')),
    sa.ForeignKeyConstraint(['capability_id'], ['supplier_capability.id'], name=op.f('fk_supplier_capability_fibre_capability_id_supplier_capability'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fibre_id', 'fibre_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_supplier_capability_fibre_fibre_reference_item', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_capability_fibre')),
    sa.UniqueConstraint('capability_id', 'fibre_id', name='uq_supplier_cap_fibre')
    )
    op.create_index(op.f('ix_supplier_capability_fibre_capability_id'), 'supplier_capability_fibre', ['capability_id'], unique=False)
    op.create_index(op.f('ix_supplier_capability_fibre_fibre_id'), 'supplier_capability_fibre', ['fibre_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('assignee_user_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=20), server_default='NORMAL', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='OPEN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['app_user.id'], name=op.f('fk_task_assignee_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    op.create_index(op.f('ix_task_assignee_user_id'), 'task', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_task_due_date'), 'task', ['due_date'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_table('unmapped_term',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=40), nullable=False),
    sa.Column('raw_text', sa.String(length=300), nullable=False),
    sa.Column('normalised', sa.String(length=300), nullable=False),
    sa.Column('occurrences', sa.Integer(), server_default='1', nullable=False),
    sa.Column('source_entity_type', sa.String(length=60), nullable=True),
    sa.Column('source_entity_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_item_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['app_user.id'], name=op.f('fk_unmapped_term_resolved_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_item_id'], ['reference_item.id'], name=op.f('fk_unmapped_term_resolved_item_id_reference_item'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unmapped_term')),
    sa.UniqueConstraint('domain', 'normalised', name='uq_unmapped_term_domain_normalised')
    )
    op.create_index(op.f('ix_unmapped_term_domain'), 'unmapped_term', ['domain'], unique=False)
    op.create_index(op.f('ix_unmapped_term_normalised'), 'unmapped_term', ['normalised'], unique=False)
    op.create_table('brand_profile',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('market_segment', sa.String(length=20), nullable=True),
    sa.Column('annual_volume_band', sa.String(length=40), nullable=True),
    sa.Column('preferred_incoterm_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_incoterm_domain', sa.String(length=40), server_default='INCOTERM', nullable=True),
    sa.Column('default_currency_id', sa.Uuid(), nullable=True),
    sa.Column('default_currency_domain', sa.String(length=40), server_default='CURRENCY', nullable=True),
    sa.Column('payment_terms_standard', sa.String(length=200), nullable=True),
    sa.Column('sustainability_requirements', sa.Text(), nullable=True),
    sa.Column('packaging_standards', sa.Text(), nullable=True),
    sa.Column('qa_protocol_doc_id', sa.Uuid(), nullable=True),
    sa.Column('vendor_manual_doc_id', sa.Uuid(), nullable=True),
    sa.Column('tech_pack_template_doc_id', sa.Uuid(), nullable=True),
    sa.Column('completeness_pct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("default_currency_domain = 'CURRENCY'", name=op.f('ck_brand_profile_default_currency_domain')),
    sa.CheckConstraint("preferred_incoterm_domain = 'INCOTERM'", name=op.f('ck_brand_profile_preferred_incoterm_domain')),
    sa.CheckConstraint('completeness_pct >= 0 AND completeness_pct <= 100', name=op.f('ck_brand_profile_brand_profile_completeness_range')),
    sa.ForeignKeyConstraint(['default_currency_id', 'default_currency_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_brand_profile_default_currency_reference_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_brand_profile_org_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preferred_incoterm_id', 'preferred_incoterm_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_brand_profile_preferred_incoterm_reference_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['qa_protocol_doc_id'], ['document.id'], name=op.f('fk_brand_profile_qa_protocol_doc_id_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tech_pack_template_doc_id'], ['document.id'], name=op.f('fk_brand_profile_tech_pack_template_doc_id_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_manual_doc_id'], ['document.id'], name=op.f('fk_brand_profile_vendor_manual_doc_id_document'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('org_id', name=op.f('pk_brand_profile'))
    )
    op.create_index(op.f('ix_brand_profile_default_currency_id'), 'brand_profile', ['default_currency_id'], unique=False)
    op.create_index(op.f('ix_brand_profile_market_segment'), 'brand_profile', ['market_segment'], unique=False)
    op.create_index(op.f('ix_brand_profile_preferred_incoterm_id'), 'brand_profile', ['preferred_incoterm_id'], unique=False)
    op.create_table('supplier_certification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('certification_id', sa.Uuid(), nullable=False),
    sa.Column('certification_domain', sa.String(length=40), server_default='CERTIFICATION', nullable=False),
    sa.Column('certificate_no', sa.String(length=120), nullable=True),
    sa.Column('issuing_body', sa.String(length=200), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('valid_till', sa.Date(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('source', sa.String(length=20), server_default='SELF_REPORTED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("certification_domain = 'CERTIFICATION'", name=op.f('ck_supplier_certification_certification_domain')),
    sa.ForeignKeyConstraint(['certification_id', 'certification_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_supplier_certification_certification_reference_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_supplier_certification_document_id_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_supplier_certification_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_certification')),
    sa.UniqueConstraint('org_id', 'certification_id', 'certificate_no', name='uq_supplier_cert_org_cert_no')
    )
    op.create_index('ix_supplier_cert_active', 'supplier_certification', ['org_id', 'certification_id', 'valid_till'], unique=False)
    op.create_index(op.f('ix_supplier_certification_certification_id'), 'supplier_certification', ['certification_id'], unique=False)
    op.create_index(op.f('ix_supplier_certification_org_id'), 'supplier_certification', ['org_id'], unique=False)
    op.create_index(op.f('ix_supplier_certification_valid_till'), 'supplier_certification', ['valid_till'], unique=False)
    op.create_index(op.f('ix_supplier_certification_verification_status'), 'supplier_certification', ['verification_status'], unique=False)
    op.create_table('supplier_compliance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('audit_type_id', sa.Uuid(), nullable=False),
    sa.Column('audit_type_domain', sa.String(length=40), server_default='COMPLIANCE_AUDIT_TYPE', nullable=False),
    sa.Column('audit_body', sa.String(length=200), nullable=True),
    sa.Column('audit_date', sa.Date(), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('findings_summary', sa.Text(), nullable=True),
    sa.Column('capa_status', sa.String(length=40), nullable=True),
    sa.Column('next_audit_due', sa.Date(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("audit_type_domain = 'COMPLIANCE_AUDIT_TYPE'", name=op.f('ck_supplier_compliance_audit_type_domain')),
    sa.ForeignKeyConstraint(['audit_type_id', 'audit_type_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_supplier_compliance_audit_type_reference_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_supplier_compliance_document_id_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], name=op.f('fk_supplier_compliance_org_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_compliance'))
    )
    op.create_index(op.f('ix_supplier_compliance_audit_type_id'), 'supplier_compliance', ['audit_type_id'], unique=False)
    op.create_index(op.f('ix_supplier_compliance_next_audit_due'), 'supplier_compliance', ['next_audit_due'], unique=False)
    op.create_index(op.f('ix_supplier_compliance_org_id'), 'supplier_compliance', ['org_id'], unique=False)
    # ### end Alembic commands ###


    for name, column in _CYCLIC_FKS:
        op.create_foreign_key(
            name, "organization", "app_user", [column], ["id"], ondelete="SET NULL"
        )


def downgrade() -> None:
    for name, _column in _CYCLIC_FKS:
        op.drop_constraint(name, "organization", type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_compliance_org_id'), table_name='supplier_compliance')
    op.drop_index(op.f('ix_supplier_compliance_next_audit_due'), table_name='supplier_compliance')
    op.drop_index(op.f('ix_supplier_compliance_audit_type_id'), table_name='supplier_compliance')
    op.drop_table('supplier_compliance')
    op.drop_index(op.f('ix_supplier_certification_verification_status'), table_name='supplier_certification')
    op.drop_index(op.f('ix_supplier_certification_valid_till'), table_name='supplier_certification')
    op.drop_index(op.f('ix_supplier_certification_org_id'), table_name='supplier_certification')
    op.drop_index(op.f('ix_supplier_certification_certification_id'), table_name='supplier_certification')
    op.drop_index('ix_supplier_cert_active', table_name='supplier_certification')
    op.drop_table('supplier_certification')
    op.drop_index(op.f('ix_brand_profile_preferred_incoterm_id'), table_name='brand_profile')
    op.drop_index(op.f('ix_brand_profile_market_segment'), table_name='brand_profile')
    op.drop_index(op.f('ix_brand_profile_default_currency_id'), table_name='brand_profile')
    op.drop_table('brand_profile')
    op.drop_index(op.f('ix_unmapped_term_normalised'), table_name='unmapped_term')
    op.drop_index(op.f('ix_unmapped_term_domain'), table_name='unmapped_term')
    op.drop_table('unmapped_term')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_due_date'), table_name='task')
    op.drop_index(op.f('ix_task_assignee_user_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_supplier_capability_fibre_fibre_id'), table_name='supplier_capability_fibre')
    op.drop_index(op.f('ix_supplier_capability_fibre_capability_id'), table_name='supplier_capability_fibre')
    op.drop_table('supplier_capability_fibre')
    op.drop_index(op.f('ix_supplier_capability_construction_construction_id'), table_name='supplier_capability_construction')
    op.drop_index(op.f('ix_supplier_capability_construction_capability_id'), table_name='supplier_capability_construction')
    op.drop_table('supplier_capability_construction')
    op.drop_index(op.f('ix_otp_challenge_user_id'), table_name='otp_challenge')
    op.drop_index(op.f('ix_otp_challenge_destination'), table_name='otp_challenge')
    op.drop_table('otp_challenge')
    op.drop_index(op.f('ix_org_invite_token_hash'), table_name='org_invite')
    op.drop_index(op.f('ix_org_invite_org_id'), table_name='org_invite')
    op.drop_table('org_invite')
    op.drop_index(op.f('ix_notification_preference_user_id'), table_name='notification_preference')
    op.drop_table('notification_preference')
    op.drop_index(op.f('ix_notification_outbox_status'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_scheduled_for'), table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_recipient_user_id'), table_name='notification_outbox')
    op.drop_index('ix_notification_outbox_inbox', table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_event_key'), table_name='notification_outbox')
    op.drop_index('ix_notification_outbox_dispatch', table_name='notification_outbox')
    op.drop_index(op.f('ix_notification_outbox_channel'), table_name='notification_outbox')
    op.drop_table('notification_outbox')
    op.drop_index(op.f('ix_note_org_id'), table_name='note')
    op.drop_index('ix_note_entity', table_name='note')
    op.drop_table('note')
    op.drop_table('import_batch')
    op.drop_index(op.f('ix_document_verification_status'), table_name='document')
    op.drop_index(op.f('ix_document_valid_till'), table_name='document')
    op.drop_index('ix_document_owner', table_name='document')
    op.drop_index(op.f('ix_document_org_id'), table_name='document')
    op.drop_index('ix_document_expiry_sweep', table_name='document')
    op.drop_index(op.f('ix_document_doc_type'), table_name='document')
    op.drop_index(op.f('ix_document_checksum_sha256'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_brand_supplier_reveal_supplier_org_id'), table_name='brand_supplier_reveal')
    op.drop_index(op.f('ix_brand_supplier_reveal_brand_org_id'), table_name='brand_supplier_reveal')
    op.drop_table('brand_supplier_reveal')
    op.drop_index(op.f('ix_activity_log_org_id'), table_name='activity_log')
    op.drop_index('ix_activity_log_org_created', table_name='activity_log')
    op.drop_index('ix_activity_log_entity', table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_actor_user_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_action'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_supplier_reference_product_category_id'), table_name='supplier_reference')
    op.drop_index(op.f('ix_supplier_reference_org_id'), table_name='supplier_reference')
    op.drop_index(op.f('ix_supplier_reference_buyer_country_id'), table_name='supplier_reference')
    op.drop_table('supplier_reference')
    op.drop_index(op.f('ix_supplier_profile_completeness_tier'), table_name='supplier_profile')
    op.drop_table('supplier_profile')
    op.drop_index(op.f('ix_supplier_process_process_type_id'), table_name='supplier_process')
    op.drop_index(op.f('ix_supplier_process_org_id'), table_name='supplier_process')
    op.drop_index('ix_supplier_process_filter', table_name='supplier_process')
    op.drop_table('supplier_process')
    op.drop_index(op.f('ix_supplier_performance_org_id'), table_name='supplier_performance')
    op.drop_table('supplier_performance')
    op.drop_index(op.f('ix_supplier_machine_org_id'), table_name='supplier_machine')
    op.drop_index(op.f('ix_supplier_machine_machine_type_id'), table_name='supplier_machine')
    op.drop_table('supplier_machine')
    op.drop_index(op.f('ix_supplier_export_market_org_id'), table_name='supplier_export_market')
    op.drop_index(op.f('ix_supplier_export_market_country_id'), table_name='supplier_export_market')
    op.drop_table('supplier_export_market')
    op.drop_index(op.f('ix_supplier_capacity_calendar_process_type_id'), table_name='supplier_capacity_calendar')
    op.drop_index(op.f('ix_supplier_capacity_calendar_org_id'), table_name='supplier_capacity_calendar')
    op.drop_index(op.f('ix_supplier_capacity_calendar_month'), table_name='supplier_capacity_calendar')
    op.drop_table('supplier_capacity_calendar')
    op.drop_index(op.f('ix_supplier_capability_product_category_id'), table_name='supplier_capability')
    op.drop_index(op.f('ix_supplier_capability_org_id'), table_name='supplier_capability')
    op.drop_index(op.f('ix_supplier_capability_currency_id'), table_name='supplier_capability')
    op.drop_table('supplier_capability')
    op.drop_index(op.f('ix_contact_org_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_brand_target_market_org_id'), table_name='brand_target_market')
    op.drop_index(op.f('ix_brand_target_market_country_id'), table_name='brand_target_market')
    op.drop_table('brand_target_market')
    op.drop_index(op.f('ix_brand_required_certification_org_id'), table_name='brand_required_certification')
    op.drop_index(op.f('ix_brand_required_certification_certification_id'), table_name='brand_required_certification')
    op.drop_table('brand_required_certification')
    op.drop_index(op.f('ix_brand_excluded_country_org_id'), table_name='brand_excluded_country')
    op.drop_index(op.f('ix_brand_excluded_country_country_id'), table_name='brand_excluded_country')
    op.drop_table('brand_excluded_country')
    op.drop_index(op.f('ix_brand_category_product_category_id'), table_name='brand_category')
    op.drop_index(op.f('ix_brand_category_org_id'), table_name='brand_category')
    op.drop_table('brand_category')
    op.drop_index(op.f('ix_app_user_status'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_role'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_phone'), table_name='app_user')
    op.drop_index('ix_app_user_org_role', table_name='app_user')
    op.drop_index(op.f('ix_app_user_org_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_reference_alias_normalised'), table_name='reference_alias')
    op.drop_table('reference_alias')
    op.drop_index('ix_organization_type_status', table_name='organization')
    op.drop_index(op.f('ix_organization_type'), table_name='organization')
    op.drop_index(op.f('ix_organization_trade_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_status'), table_name='organization')
    op.drop_index(op.f('ix_organization_import_batch_id'), table_name='organization')
    op.drop_index(op.f('ix_organization_country_id'), table_name='organization')
    op.drop_index(op.f('ix_organization_city'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_reference_item_parent_id'), table_name='reference_item')
    op.drop_index('ix_reference_item_domain_path', table_name='reference_item')
    op.drop_index(op.f('ix_reference_item_domain'), table_name='reference_item')
    op.drop_table('reference_item')
    op.drop_index(op.f('ix_notification_template_event_key'), table_name='notification_template')
    op.drop_table('notification_template')
    # ### end Alembic commands ###
