"""google sign-in and access approval

Replaces the is_active boolean with a four-state status, and adds the Google account link and
the record of who approved whom.

The autogenerated version of this was wrong in a way worth writing down: it added `status` with
its PENDING default and then dropped `is_active`, which turns every existing user — including
the only admin — into a pending request with nobody left to approve it. The backfill below
carries each row's is_active across before the old column goes.

Revision ID: 9d770db20c82
Revises: 6e92e5e88919
Create Date: 2026-09-10 16:48:50.483391
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9d770db20c82'
down_revision: str | None = '6e92e5e88919'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column('app_user', sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False))
    # Everyone who could sign in before can sign in after; anyone switched off stays off.
    op.execute("UPDATE app_user SET status = CASE WHEN is_active THEN 'ACTIVE' ELSE 'DISABLED' END")
    op.add_column('app_user', sa.Column('google_sub', sa.String(length=64), nullable=True))
    op.add_column('app_user', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('app_user', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_user', sa.Column('reviewed_by_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_app_user_status'), 'app_user', ['status'], unique=False)
    op.create_unique_constraint('uq_app_user_google_sub', 'app_user', ['google_sub'])
    op.create_foreign_key(op.f('fk_app_user_reviewed_by_id_app_user'), 'app_user', 'app_user', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
    op.create_check_constraint(op.f('ck_app_user_status_known'), 'app_user', "status IN ('PENDING', 'ACTIVE', 'REJECTED', 'DISABLED')")
    op.drop_column('app_user', 'is_active')


def downgrade() -> None:
    op.add_column('app_user', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # The boolean can't hold "waiting" or "declined"; neither of those could sign in, so both
    # map to false along with DISABLED.
    op.execute("UPDATE app_user SET is_active = (status = 'ACTIVE')")
    op.drop_constraint(op.f('ck_app_user_status_known'), 'app_user', type_='check')
    op.drop_constraint(op.f('fk_app_user_reviewed_by_id_app_user'), 'app_user', type_='foreignkey')
    op.drop_constraint('uq_app_user_google_sub', 'app_user', type_='unique')
    op.drop_index(op.f('ix_app_user_status'), table_name='app_user')
    op.drop_column('app_user', 'reviewed_by_id')
    op.drop_column('app_user', 'reviewed_at')
    op.drop_column('app_user', 'avatar_url')
    op.drop_column('app_user', 'google_sub')
    op.drop_column('app_user', 'status')
