"""connection and connection_stage: the commercial record

Revision ID: 9f67c168d81f
Revises: 16a6d6eba222
Create Date: 2026-08-25 14:45:17.044003
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9f67c168d81f'
down_revision: str | None = '16a6d6eba222'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_no', sa.String(length=24), nullable=False),
    sa.Column('brand_org_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_category_id', sa.Uuid(), nullable=True),
    sa.Column('product_category_domain', sa.String(length=40), server_default='PRODUCT_CATEGORY', nullable=True),
    sa.Column('currency_id', sa.Uuid(), nullable=True),
    sa.Column('currency_domain', sa.String(length=40), server_default='CURRENCY', nullable=True),
    sa.Column('status', sa.String(length=20), server_default='SCOPING', nullable=False),
    sa.Column('lost_reason', sa.String(length=400), nullable=True),
    sa.Column('target_ship_date', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency_domain = 'CURRENCY'", name=op.f('ck_connection_currency_domain')),
    sa.CheckConstraint("product_category_domain = 'PRODUCT_CATEGORY'", name=op.f('ck_connection_product_category_domain')),
    sa.CheckConstraint("status <> 'LOST' OR lost_reason IS NOT NULL", name=op.f('ck_connection_connection_lost_needs_reason')),
    sa.ForeignKeyConstraint(['brand_org_id'], ['organization.id'], name=op.f('fk_connection_brand_org_id_organization'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id', 'currency_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_connection_currency_reference_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], name=op.f('fk_connection_owner_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_category_id', 'product_category_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_connection_product_category_reference_item', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection')),
    sa.UniqueConstraint('connection_no', name='uq_connection_no')
    )
    op.create_index(op.f('ix_connection_brand_org_id'), 'connection', ['brand_org_id'], unique=False)
    op.create_index(op.f('ix_connection_currency_id'), 'connection', ['currency_id'], unique=False)
    op.create_index(op.f('ix_connection_owner_user_id'), 'connection', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_connection_product_category_id'), 'connection', ['product_category_id'], unique=False)
    op.create_index(op.f('ix_connection_status'), 'connection', ['status'], unique=False)
    op.create_index('ix_connection_status_ship', 'connection', ['status', 'target_ship_date'], unique=False)
    op.create_index(op.f('ix_connection_target_ship_date'), 'connection', ['target_ship_date'], unique=False)
    op.create_table('connection_stage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_org_id', sa.Uuid(), nullable=False),
    sa.Column('process_type_id', sa.Uuid(), nullable=False),
    sa.Column('process_type_domain', sa.String(length=40), server_default='PROCESS_TYPE', nullable=False),
    sa.Column('sequence', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PROPOSED', nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('qty_uom', sa.String(length=20), nullable=True),
    sa.Column('supplier_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('brand_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('order_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('commission_basis', sa.String(length=24), server_default='SUPPLIER_COMMISSION', nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('commission_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('commission_status', sa.String(length=20), server_default='NOT_DUE', nullable=False),
    sa.Column('invoiced_on', sa.Date(), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=True),
    sa.Column('ship_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("commission_basis <> 'BRAND_MARKUP' OR (supplier_price IS NOT NULL AND brand_price IS NOT NULL)", name=op.f('ck_connection_stage_connection_stage_markup_needs_prices')),
    sa.CheckConstraint("commission_basis <> 'SUPPLIER_COMMISSION' OR commission_pct IS NOT NULL", name=op.f('ck_connection_stage_connection_stage_commission_needs_pct')),
    sa.CheckConstraint("commission_status NOT IN ('INVOICED','RECEIVED') OR commission_amount IS NOT NULL", name=op.f('ck_connection_stage_connection_stage_billed_needs_amount')),
    sa.CheckConstraint("process_type_domain = 'PROCESS_TYPE'", name=op.f('ck_connection_stage_process_type_domain')),
    sa.CheckConstraint('brand_price IS NULL OR supplier_price IS NULL OR brand_price >= supplier_price', name=op.f('ck_connection_stage_connection_stage_markup_not_negative')),
    sa.CheckConstraint('commission_amount IS NULL OR commission_amount >= 0', name=op.f('ck_connection_stage_connection_stage_commission_not_negative')),
    sa.CheckConstraint('received_on IS NULL OR invoiced_on IS NULL OR received_on >= invoiced_on', name=op.f('ck_connection_stage_connection_stage_received_after_invoiced')),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], name=op.f('fk_connection_stage_connection_id_connection'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_type_id', 'process_type_domain'], ['reference_item.id', 'reference_item.domain'], name='fk_connection_stage_process_type_reference_item', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_org_id'], ['organization.id'], name=op.f('fk_connection_stage_supplier_org_id_organization'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection_stage')),
    sa.UniqueConstraint('connection_id', 'supplier_org_id', 'process_type_id', name='uq_connection_stage_supplier_process')
    )
    op.create_index(op.f('ix_connection_stage_commission_status'), 'connection_stage', ['commission_status'], unique=False)
    op.create_index(op.f('ix_connection_stage_connection_id'), 'connection_stage', ['connection_id'], unique=False)
    op.create_index('ix_connection_stage_ledger', 'connection_stage', ['commission_status', 'received_on'], unique=False)
    op.create_index(op.f('ix_connection_stage_process_type_id'), 'connection_stage', ['process_type_id'], unique=False)
    op.create_index(op.f('ix_connection_stage_received_on'), 'connection_stage', ['received_on'], unique=False)
    op.create_index(op.f('ix_connection_stage_ship_date'), 'connection_stage', ['ship_date'], unique=False)
    op.create_index(op.f('ix_connection_stage_status'), 'connection_stage', ['status'], unique=False)
    op.create_index('ix_connection_stage_supplier', 'connection_stage', ['supplier_org_id', 'status'], unique=False)
    op.create_index(op.f('ix_connection_stage_supplier_org_id'), 'connection_stage', ['supplier_org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_stage_supplier_org_id'), table_name='connection_stage')
    op.drop_index('ix_connection_stage_supplier', table_name='connection_stage')
    op.drop_index(op.f('ix_connection_stage_status'), table_name='connection_stage')
    op.drop_index(op.f('ix_connection_stage_ship_date'), table_name='connection_stage')
    op.drop_index(op.f('ix_connection_stage_received_on'), table_name='connection_stage')
    op.drop_index(op.f('ix_connection_stage_process_type_id'), table_name='connection_stage')
    op.drop_index('ix_connection_stage_ledger', table_name='connection_stage')
    op.drop_index(op.f('ix_connection_stage_connection_id'), table_name='connection_stage')
    op.drop_index(op.f('ix_connection_stage_commission_status'), table_name='connection_stage')
    op.drop_table('connection_stage')
    op.drop_index(op.f('ix_connection_target_ship_date'), table_name='connection')
    op.drop_index('ix_connection_status_ship', table_name='connection')
    op.drop_index(op.f('ix_connection_status'), table_name='connection')
    op.drop_index(op.f('ix_connection_product_category_id'), table_name='connection')
    op.drop_index(op.f('ix_connection_owner_user_id'), table_name='connection')
    op.drop_index(op.f('ix_connection_currency_id'), table_name='connection')
    op.drop_index(op.f('ix_connection_brand_org_id'), table_name='connection')
    op.drop_table('connection')
    # ### end Alembic commands ###
